### ISSUE TITLE
Issues in Month View and Day View

### ISSUE THREAD

**Issue by vcdotwine** [danheron/Heron.MudTotalCalendar#11]
Dan, first let me say that this solution is amazing! Thank you for working on it.

Two issues we're currently facing.

Issue No. 1
In month view, the CellClicked API event not working. The cells are not buttons. It does work in Week and Month View.

Issue No. 2
In day view, events or items are not being shown.

Thank you for taking a look at these!

**Comment by danheron** [comment]
Thanks for the feedback!

Issue 1 - I will fix.

Issue 2 - I can't recreate.  Is it just a problem in Day view?  The items are shown in Week view?  Do you have some example code that shows the problem?
