### ISSUE TITLE
OpenTo DatePicker

### ISSUE THREAD

**Issue by Tiempien** [danheron/Heron.MudTotalCalendar#13]
It's a great extension for my Mudblazor project,  But I am missing the ability of the datepicker to use OpenTo (https://mudblazor.com/components/datepicker#fixed-values-usage).

I'm guessing it's a minor change because you only pass the OpenTo Attribute to the datepicker.
And I'm guessing it's worth adding

**Comment by danheron** [comment]
You can go to any date by setting the 'CurrentDay' property.  The datepicker will also open to this date.

Is that good enough?  Or do you need the datepicker to open to a different date than the calendar?

**Comment by danheron** [comment]
Closing because of no response.
