### ISSUE TITLE
DateRangeChanged invoked twice for the same date range

### ISSUE THREAD

**Issue by SeanFeldman** [danheron/Heron.MudTotalCalendar#17]
When the control is loaded, the date range change is fired once.
When navigating between dates, the callback is invoked twice rather than once for each navigation.
<img width="140" alt="image" src="https://github.com/danheron/Heron.MudTotalCalendar/assets/1309622/f005aec4-6964-4166-9c93-311d5e7b2b7d">

**Comment by danheron** [comment]
This was fixed in an earlier release of Heron.MudCalendar.

I will update the dependencies.
