### ISSUE TITLE
About the FirstDayOfWeek settings

### ISSUE THREAD

**Issue by inorino** [danheron/Heron.MudTotalCalendar#21]
Hello Heron,
I am a fan from Taiwan of the MudTotalCalendar suite. Recently, I encountered a situation where I need to use Monday as the first day of the week. I would like to ask if you can increase this API.

I confirmed that the Mudblazer suite's DatePicker can now be set using FirstDayOfWeek.［https://mudblazor.com/api/datepicker#pages］

I wonder if you can please add this function so that both MudTotalCalendar and ShowDatePicker can adjust to a custom API (Ex.FirstDayOfWeek) as the first day of each week. Thank you very much for your efforts.

**Comment by danheron** [comment]
MudTotalCalendar will use the day that is set in the current culture.  Hopefully that will work for you.

However I will consider adding an extra property to be consistent with MudBlazor.

**Comment by inorino** [comment]
Thanks for your suggestion. I tried to modify the setting in the current culture and have been able to successfully adjust Monday as the first day of the week. Thank you for your generous help.

I will continue to look forward to any further updates on this project, thank you.

**Comment by danheron** [comment]
MudTotalCalendar now has a FirstDayOfWeek property.
