### ISSUE TITLE
ShowDay and ShowWeek are not working

### ISSUE THREAD

**Issue by vcdotwine** [danheron/Heron.MudTotalCalendar#9]
I have tried using ShowDay and ShowWeek with MudTotalCalendar properties, but they are not working.

This is the code that I am using:
`<MudTotalCalendar Values="BuildTotals()" Items="_schedule" Height="600" ShowDay="true" ShowWeek="true">
`
I've also tried setting the boolean without the quotes. Same result.

This is the result:
![Screenshot 2023-05-24 at 8 14 37 AM](https://github.com/danheron/Heron.MudTotalCalendar/assets/61473848/8ef5598c-98cf-43f0-b182-ac91a3166017)

**Comment by danheron** [comment]
OK, I will fix that.
